### ISSUE TITLE
[Request]:  Allow more participants in the zoom meeting

### ISSUE THREAD

**Issue by ADIthaker** [rust-lang/rustc-reading-club#20]
### Organizer Request

I am unable to join the meeting on zoom, i keep getting the message " the meeting has reached maximum capacity"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zshell31** [comment]
The same problem, I've got the message
![Screenshot from 2021-11-04 19-10-20](https://user-images.githubusercontent.com/2960336/140376564-32b68894-ee00-4f1d-b230-2eb70f7997a0.png)

**Comment by PureWhiteWu** [comment]
Maybe we could try [Lark Meeting](https://meetings.larksuite.com/) which can host at most 350 people (and up to 1000 for paid version).
And there's a surprise that Lark is written in Rust.

**Comment by shahidkhan021** [comment]
did anybody able to join meeting

**Comment by shahidkhan021** [comment]
did anybody able to join meeting

**Comment by ghost** [comment]
I don't have admin rights on my work machine and was able to download, install and load lark without issues.

**Comment by doc-jones** [comment]
Unfortunately, the code reading club was more popular than we expected and Zoom has a hard limit for 100 attendees. Niko the leader of the session couldn't join. We cancelled today's session because Niko couldn't join and because the format doesn't scale to have 100 people offer their opinions in zoom on what they found interesting in the code.

We will regroup and figure out how to set criteria for joining to hold down attendance to a manageable level. At the same time, we hope to recruit more sessions leaders and organizers.  We want to offer enough sessions to meet the demand, but be patient as we figure things out.
